apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden-sm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitwarden.com/
    targetRevision: 1.0.0
    chart: sm-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: sm-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
