apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden-sm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://charts.longhorn.io/
    targetRevision: v1.9.1
    chart: longhorn
    helm:
      valueFiles:
      - $values/app_configs/longhorn_values.yaml
  - repoURL: 'https://github.com/pkking/homelab.git'
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
