apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: bitwarden-secret
spec:
  project: default
  source:
    path: crds/postgresql
    repoURL: "https://github.com/pkking/homelab"
    targetRevision: HEAD
  destination:
    namespace: postgres
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
