---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  targetNamespaces:
    - postgres-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cloudnative-pg
  namespace: cloudnative-pg-operator
spec:
  channel: "stable-v1"
  installPlanApproval: "Automatic"
  name: "cloudnative-pg"
  source: "operatorhubio-catalog"
  sourceNamespace: "olm"
  startingCSV: "1.27.0"
