apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
spec:
  description: "postgresql for pkking homelab"
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: postgresql
    major: 17
  instances: 1
  superuserSecret:
    name: pg-superuser
  enableSuperuserAccess: true
  storage:
    size: 10Gi
    storageClass: "synology-csi-nfs-retain"
  postgresql:
    pg_hba:
      - host all all 10.42.0.0/16 password
  bootstrap:
    initdb:
      database: n8n
      owner: n8n
      secret:
        name: n8n-user
    # Alternative bootstrap method: start from a backup
    #recovery:
    #  backup:
    #    name: backup-example
