apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volume-snapshot
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: deploy/kubernetes/snapshot-controller
    repoURL: "https://github.com/kubernetes-csi/external-snapshotter.git"
    targetRevision: master
  destination:
    namespace: kube-system
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
