apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: common-snapshot-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    path: deploy/kubernetes/snapshot-controller
    repoURL: https://github.com/kubernetes-csi/external-snapshotter.git
    targetRevision: v8.3.0
  destination:
    namespace: kube-system
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
