apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    path: crds/n8n
    repoURL: "https://github.com/pkking/homelab.git"
    targetRevision: main
  destination:
    namespace: n8n
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
