apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    # see https://artifacthub.io/packages/helm/community-charts/n8n
    - repoURL: https://artifacthub.io/packages/helm/community-charts/n8n
      targetRevision: 1.15.12
      chart: n8n
      helm:
        valueFiles:
          - $values/app_configs/n8n_values.yaml
    - repoURL: "https://github.com/pkking/homelab.git"
      targetRevision: main
      ref: values
  destination:
    namespace: n8n
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true